# Generated by Django 4.2.4 on 2023-09-02 12:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0002_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='video/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='images/'),
            preserve_default=False,
        ),
    ]
