# Generated by Django 4.2.4 on 2023-09-08 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0003_alter_video_file_alter_video_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
