# Generated by Django 4.2.5 on 2023-09-19 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0006_video_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='content',
        ),
    ]
