# Generated by Django 4.2.5 on 2023-09-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0008_video_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='content',
            field=models.TextField(unique=True),
        ),
    ]
