# Generated by Django 4.2.5 on 2023-09-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0011_video_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Series_Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
