# Generated by Django 4.2.5 on 2023-09-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0012_series_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_name',
            name='poster',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
