# Generated by Django 4.2.5 on 2023-09-25 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0013_series_name_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='series',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload_video.series_name'),
        ),
    ]
