# Generated by Django 4.2.5 on 2023-10-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0014_video_series'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_name',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
