# Generated by Django 4.2.5 on 2023-10-06 13:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0017_series_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_name',
            name='detail',
            field=models.CharField(default=django.utils.timezone.now, max_length=500),
            preserve_default=False,
        ),
    ]
