# Generated by Django 4.2.5 on 2023-10-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0018_series_name_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_name',
            name='detail',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
