# Generated by Django 4.2.5 on 2023-10-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0019_alter_series_name_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_name',
            name='detail',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
