# Generated by Django 4.2.5 on 2023-10-25 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0021_series_name_genre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series_name',
            options={'ordering': ['-time_stamp']},
        ),
    ]
