# Generated by Django 4.2.5 on 2023-10-31 03:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0022_alter_series_name_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='login',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='login',
            name='username',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
