# Generated by Django 3.2.24 on 2024-10-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0024_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series_name',
            name='Name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
