# Generated by Django 3.2.24 on 2024-10-10 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0026_series_name_view_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='series_name',
            name='view_count',
        ),
    ]
