# Generated by Django 3.2.24 on 2024-10-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0027_remove_series_name_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
