# Generated by Django 3.2.24 on 2024-10-10 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0028_video_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='series_name',
            name='count_views',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
