# Generated by Django 4.2.5 on 2023-10-27 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0022_alter_series_name_options'),
        ('mylist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mylist',
            name='my_list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload_video.series_name'),
        ),
    ]
