# Generated by Django 4.2.5 on 2023-10-29 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('upload_video', '0022_alter_series_name_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watch_History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('video_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload_video.series_name')),
            ],
        ),
    ]
