# Generated by Django 4.2.5 on 2023-10-29 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchhistory', '0002_alter_watch_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch_history',
            options={'ordering': ['timestamp']},
        ),
    ]
