# Generated by Django 4.2.5 on 2023-10-30 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchhistory', '0003_alter_watch_history_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watch_history',
            options={},
        ),
    ]
