# Generated by Django 3.2.24 on 2024-10-11 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload_video', '0029_series_name_count_views'),
        ('watchhistory', '0007_alter_watch_history_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch_history',
            name='video_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='upload_video.video'),
        ),
    ]
